name: LittleDarwin Test Suite

on:
  push:
    branches: [ master, quick-quicker ]
  pull_request:
    branches: [ master, quick-quicker ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install --upgrade pytest 
        pytest -l --verbosity=3
